name: Deploy to Server
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/deploy_key
          # Fix line endings and permissions
          sed -i 's/\r$//' ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan 138.197.174.176 >> ~/.ssh/known_hosts

          
      - name: Deploy
        run: |
          ssh -i ~/.ssh/deploy_key root@138.197.174.176 "
            cd /root/finalback
            git pull origin main
            yarn install --frozen-lockfile
            yarn build
            pm2 restart finalback
            # Add restart commands here
          "
